//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinancePlotter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FinancePlotter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date,Open,High,Low,Close,Volume,Adj Close
        ///2014-06-06,649.90,651.26,644.47,645.57,12497800,645.57
        ///2014-06-05,646.20,649.37,642.61,647.35,10850200,647.35
        ///2014-06-04,637.44,647.89,636.11,644.82,11981500,644.82
        ///2014-06-03,628.46,638.74,628.25,637.54,10453900,637.54
        ///2014-06-02,633.96,634.83,622.50,628.65,13191100,628.65
        ///2014-05-30,637.98,644.17,628.90,633.00,20143600,633.00
        ///2014-05-29,627.85,636.87,627.77,635.38,13445500,635.38
        ///2014-05-28,626.02,629.83,623.78,624.01,11267200,624.01
        ///2014-05-27,615.88,625 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string apple {
            get {
                return ResourceManager.GetString("apple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date,Open,High,Low,Close,Volume,Adj Close
        ///2014-06-06,63.37,63.48,62.15,62.50,42386300,62.50
        ///2014-06-05,63.66,64.36,62.82,63.19,47352000,63.19
        ///2014-06-04,62.45,63.59,62.07,63.34,36514000,63.34
        ///2014-06-03,62.62,63.42,62.32,62.87,32217000,62.87
        ///2014-06-02,63.23,63.59,62.05,63.08,35947400,63.08
        ///2014-05-30,63.95,64.17,62.56,63.30,45253500,63.30
        ///2014-05-29,63.84,64.30,63.51,63.83,42700000,63.83
        ///2014-05-28,63.39,64.14,62.62,63.51,47795000,63.51
        ///2014-05-27,61.62,63.51,61.57,63.48,55682000,63.48
        ///2014-05-23 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date,Open,High,Low,Close,Volume,Adj Close
        ///2014-06-06,41.48,41.66,41.24,41.48,24043600,41.48
        ///2014-06-05,40.59,41.25,40.40,41.21,31865200,41.21
        ///2014-06-04,40.21,40.37,39.86,40.32,23209000,40.32
        ///2014-06-03,40.60,40.68,40.25,40.29,18068900,40.29
        ///2014-06-02,40.95,41.09,40.68,40.79,18504300,40.79
        ///2014-05-30,40.45,40.97,40.25,40.94,34567600,40.94
        ///2014-05-29,40.15,40.35,39.91,40.34,19888200,40.34
        ///2014-05-28,40.14,40.19,39.82,40.01,25711500,40.01
        ///2014-05-27,40.26,40.26,39.81,40.19,26160600,40.19
        ///2014-05-23 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Microsoft {
            get {
                return ResourceManager.GetString("Microsoft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date,Open,High,Low,Close,Volume,Adj Close
        ///2014-06-06,34.14,34.41,33.22,33.33,23339800,33.33
        ///2014-06-05,33.67,34.89,33.11,33.89,40904900,33.89
        ///2014-06-04,32.49,33.32,31.85,32.90,24863000,32.90
        ///2014-06-03,31.73,32.69,31.65,32.58,19948800,32.58
        ///2014-06-02,32.89,33.20,31.62,31.75,31154200,31.75
        ///2014-05-30,33.73,33.86,32.11,32.44,40566000,32.44
        ///2014-05-29,34.67,35.14,33.88,34.00,54016300,34.00
        ///2014-05-28,31.50,33.84,31.09,33.77,60302800,33.77
        ///2014-05-27,30.94,31.20,30.38,30.51,25240100,30.51
        ///2014-05-23 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
    }
}
